Домашнее задание к лекции №5
arsvrn/fin-tech-java-2024 pull request #4
Opened 2024-09-25 14:42 UTC by arsvrn

2024-09-29 19:34 UTC, SHvatov requested changes
@arsvrn оставил комментарии, посмотри их, пожалуйста.

2024-09-29 19:34 UTC, SHvatov commented on src/main/java/com/tbank/edu/hw5/repository/CategoryRepository.java
> +public class CategoryRepository implements ICategoryRepository {
`ICategoryRepository` - `I<interface name>` - это больше про C# и компанию. Да и в скором времени вы переедете на Spring Data, и данный класс станет интерфейсом. Давай построим вот такую иерархию:

```
              CrudRepository<T>
           |                    |
CategoryRepository    LocationRepository
```

```java
AbstractCrudRepository implements CrudRepository
CategoryRepositoryImpl extends AbstractCrudRepository implements CategoryRepository
Location...
```

2024-09-29 19:34 UTC, SHvatov commented on src/main/java/com/tbank/edu/hw5/service/ExternalApiService.java
> +        Category[] categories = restTemplate.getForObject("https://kudago.com/public-api/v1.4/place-categories", Category[].class);
1. Урлы в константы
2. Стоит добавить обработку ошибок

2024-09-29 19:34 UTC, SHvatov commented on src/main/java/com/tbank/edu/hw5/service/ExternalApiService.java
> +public class ExternalApiService {
Не вижу его использований и пункта `Кастомное поведение при старте`

2024-10-02 18:23 UTC, arsvrn commented
@SHvatov доработал код, посмотри, пожалуйста

2024-10-03 09:10 UTC, SHvatov approved these changes
@arsvrn 👍

2024-10-03 20:19 UTC, merged